// <auto-generated />
// This file was generated by R4Mvc.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the r4mvc.json file (i.e. the settings file), save it and run the generator tool again.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo.Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
#pragma warning disable 1591, 3008, 3009, 0108
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Threading.Tasks;
using System.Web;
using System.Web.Routing;
using System.Web.Mvc;
using T4MVC;

namespace TestMvc5Application.Controllers
{
    public partial class UserController
    {
        [GeneratedCode("R4Mvc5", "1.0"), DebuggerNonUserCode]
        public UserController()
        {
        }

        [GeneratedCode("R4Mvc5", "1.0"), DebuggerNonUserCode]
        protected UserController(Dummy d)
        {
        }

        [GeneratedCode("R4Mvc5", "1.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("R4Mvc5", "1.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("R4Mvc5", "1.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("R4Mvc5", "1.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("R4Mvc5", "1.0"), DebuggerNonUserCode]
        public virtual ActionResult Details()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Details);
        }

        [GeneratedCode("R4Mvc5", "1.0"), DebuggerNonUserCode]
        public UserController Actions => MVC.User;
        [GeneratedCode("R4Mvc5", "1.0")]
        public readonly string Area = "";
        [GeneratedCode("R4Mvc5", "1.0")]
        public readonly string Name = "User";
        [GeneratedCode("R4Mvc5", "1.0")]
        public const string NameConst = "User";
        [GeneratedCode("R4Mvc5", "1.0")]
        static readonly ActionNamesClass s_ActionNames = new ActionNamesClass();
        [GeneratedCode("R4Mvc5", "1.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames => s_ActionNames;
        [GeneratedCode("R4Mvc5", "1.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Details = "Details";
        }

        [GeneratedCode("R4Mvc5", "1.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Details = "Details";
        }

        [GeneratedCode("R4Mvc5", "1.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames => s_ViewNames;
            public class _ViewNamesClass
            {
                public readonly string Details = "Details";
            }

            public readonly string Details = "~/Views/User/Details.cshtml";
        }

        [GeneratedCode("R4Mvc5", "1.0")]
        static readonly ViewsClass s_Views = new ViewsClass();
        [GeneratedCode("R4Mvc5", "1.0"), DebuggerNonUserCode]
        public ViewsClass Views => s_Views;
    }

    [GeneratedCode("R4Mvc5", "1.0"), DebuggerNonUserCode]
    public partial class T4MVC_UserController : TestMvc5Application.Controllers.UserController
    {
        public T4MVC_UserController(): base(Dummy.Instance)
        {
        }

        [NonAction]
        partial void DetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, string name);
        [NonAction]
        public override System.Web.Mvc.ActionResult Details(int id, string name)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Details);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "name", name);
            DetailsOverride(callInfo, id, name);
            return callInfo;
        }

        [NonAction]
        partial void DetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, TestMvc5Application.Models.User.UserDetails model);
        [NonAction]
        public override System.Web.Mvc.ActionResult Details(TestMvc5Application.Models.User.UserDetails model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Details);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            DetailsOverride(callInfo, model);
            return callInfo;
        }
    }
}
#pragma warning restore 1591, 3008, 3009, 0108
